[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run lint:check && npm test && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 3

[services.backend]
source = "."
build.builder = "nixpacks"

[environments.production]
name = "stormneighbor-backend-prod"

[environments.staging]  
name = "stormneighbor-backend-staging"